version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql://ryan:mcu@db:5432/whatif?schema=public
    ports:
      - "4000:4000"
      - "4001:4001"
  db:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: ryan
      POSTGRES_PASSWORD: mcu
      POSTGRES_DB: whatif
    ports:
      - "5433:5432"
