version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./:/app
  # postgres:
    # image: postgres:9.6.2-alpine
    # environment:
    #   POSTGRES_USER: ryan
    #   POSTGRES_DB: test